### ISSUE TITLE
Create Domain failed

### ISSUE THREAD

**Issue by sujansonly** [jeqo/oracle-fmw#1]
```
   Running handlers:
   [2015-03-25T13:37:26-05:00] ERROR: Running exception handlers
   Running handlers complete
   [2015-03-25T13:37:26-05:00] ERROR: Exception handlers complete
   [2015-03-25T13:37:26-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   Chef Client failed. 5 resources updated in 240.215734177 seconds
   [2015-03-25T13:37:26-05:00] ERROR: execute[/home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py] (oracle-fmw
```

::create-domain-12c line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
       STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

```
   Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not
```

return a prompt right away.

```
   Welcome to WebLogic Server Administration Scripting Shell

   Type help() for help on available commands

   Creating Domain
   Adding Templates
   Creating Resources
   Error: cd() failed. Do dumpStack() to see details.
   STDERR: Problem invoking WLST - Traceback (innermost last):
     File "/tmp/kitchen/cache/new_domain-12c.py", line 66, in ?
     File "/tmp/kitchen/cache/new_domain-12c.py", line 16, in alterDatasource
     File "/tmp/WLSTOfflineIni5449516747795960387.py", line 23, in cd
    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
    at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
    at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1069)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

   com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: java.lang.UnsupportedOperationException: Could not
```

 create generic operation:JDBCDriverParams
       ---- End output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
       Ran /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py returned 1
       [2015-03-25T18:37:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

> > > > > > Converge failed on instance <systinet-dev-Corp-OEL>.
> > > > > > Please see .kitchen/logs/systinet-dev-Corp-OEL.log for more details
> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: SSH exited (1) for command: [sh -c '
> > > > > > sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json

below is the order i have been trying to install 

include_recipe "oracle-fmw::prepare-environment-12c"
include_recipe "oracle-fmw::install-bpm_qs-12c"
include_recipe "oracle-fmw::create-rcu_repository-12c"
include_recipe "oracle-fmw::create-domain-12c"

**Comment by sujansonly** [comment]
issues has been resolved, it was due to network connection lost.
