### ISSUE TITLE
create-domain-12c is failing

### ISSUE THREAD

**Issue by sujansonly** [jeqo/oracle-fmw#3]
Hi, create domain script has failed for me with below error

Generated at 2015-05-12 08:47:15 -0500
Mixlib::ShellOut::ShellCommandFailed: execute[/home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py](oracle-fmw::create-domain-12c line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Adding Templates
Creating Resources
Error: cd() failed. Do dumpStack() to see details.
STDERR: Problem invoking WLST - Traceback (innermost last):
  File "/tmp/kitchen/cache/new_domain-12c.py", line 66, in ?
  File "/tmp/kitchen/cache/new_domain-12c.py", line 16, in alterDatasource
  File "/tmp/WLSTOfflineIni1379176903898246675.py", line 23, in cd
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
        at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1069)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: java.lang.UnsupportedOperationException: Could not create generic operation:JDBCDriverParams
---- End output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
Ran /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:267:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:254:in`error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:60:in`block in action_run'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in`add_action'

am i missing anything, could you please suggest if you have faced this error before

**Comment by sujansonly** [comment]
looks like issue with the JDBC formed URL 
default['domain-12c']['db_repo_url'] = "jdbc:oracle:thin:@#{node['domain-12c']['db_repo_host']}:#{node['domain-12c']['db_repo_port']}#{node['domain-12c']['db_repo_sid']}"

i have added / before sid value, 

```
   Chef Client failed. 82 resources updated in 1736.412947706 seconds
   [2015-05-12T15:09:04-05:00] ERROR: execute[/home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py] (oracle-fmw
```

::create-domain-12c line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
       STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

```
   Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not
```

return a prompt right away.

```
   Welcome to WebLogic Server Administration Scripting Shell

   Type help() for help on available commands
   STDERR: Problem invoking WLST - Traceback (innermost last):
     (no code object) at line 0
     File "/tmp/kitchen/cache/new_domain-12c.py", line 11
    REPOS_DBURL='jdbc:oracle:thin:@10.227.91.250:1521#{node['domain-12c']['db_repo_sid']}'
                                                             ^
   SyntaxError: invalid syntax
   ---- End output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
   Ran /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py returned 1
   [2015-05-12T20:09:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jeqo** [comment]
Hi Sujan,

Are you passing the [domain-12c][db_repo_sid] variable? Looks like it's not
set and the string with the variable insertion is causing the problem.

Try to update your Role or your vagrant configuration to pass this
variable, and try again.

Let me know how its going

Regards,
Jorge

**Comment by sujansonly** [comment]
apologies for mis routing the issue.
i have hardcoded the SID but i see the below error stilll

```
   Running handlers:
   [2015-05-12T17:48:45-05:00] ERROR: Running exception handlers
   Running handlers complete
   [2015-05-12T17:48:45-05:00] ERROR: Exception handlers complete
   [2015-05-12T17:48:45-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   Chef Client failed. 19 resources updated in 773.305256074 seconds
   [2015-05-12T17:48:45-05:00] ERROR: execute[/home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py] (oracle-fmw
```

::create-domain-12c line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
       STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

```
   Welcome to WebLogic Server Administration Scripting Shell

   Type help() for help on available commands

   Creating Domain
   Adding Templates
   Creating Resources
   Error: cd() failed. Do dumpStack() to see details.
   STDERR: Problem invoking WLST - Traceback (innermost last):
     File "/tmp/kitchen/cache/new_domain-12c.py", line 66, in ?
     File "/tmp/kitchen/cache/new_domain-12c.py", line 16, in alterDatasource
     File "/tmp/WLSTOfflineIni1981345556751361757.py", line 23, in cd
    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
    at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
    at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1069)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

   com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: java.lang.UnsupportedOperationException: Could not
```

 create generic operation:JDBCDriverParams
       ---- End output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
       Ran /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py returned 1
       [2015-05-12T22:48:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

> > > > > > Converge failed on instance <soa-dev-Corp-OEL>.
> > > > > > Please see .kitchen/logs/soa-dev-Corp-OEL.log for more details
> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: SSH exited (1) for command: [sh -c '
> > > > > > sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
> > > > > > ']

**Comment by sujansonly** [comment]
Hi Jeqo,

for the same issue, just updating the domain name to soa has passed above step i guess. but i see this error now. do you have any clue

Generated at 2015-05-13 15:09:01 -0500
Mixlib::ShellOut::ShellCommandFailed: execute[/home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py](oracle-fmw::create-domain-12c line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Adding Templates
Creating Resources
Error: cd() failed. Do dumpStack() to see details.
STDERR: Problem invoking WLST - Traceback (innermost last):
  File "/tmp/kitchen/cache/new_domain-12c.py", line 80, in ?
  File "/tmp/kitchen/cache/new_domain-12c.py", line 25, in defineServer
  File "/tmp/WLSTOfflineIni5230851962971625771.py", line 23, in cd
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
        at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1069)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.ScriptException: No Server object with name AdminServer
---- End output of /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py ----
Ran /home/oracle-fmw/fmw/bpm_qs/12c/wlserver/common/bin/wlst.sh /tmp/kitchen/cache/new_domain-12c.py returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:267:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:254:in`error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:60:in`block in action_run'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in`add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:59:in`action_run'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'

**Comment by jeqo** [comment]
Hi Sujan, 

This message ("com.oracle.cie.domain.script.ScriptException: No Server object with name AdminServer") says the Admin Server is not defined in your domain. This is uncommon because all the domain templates creates an Admin Server with that name.

Could you kindly update the WLST script to check it? You can get it here: /tmp/kitchen/cache/new_domain-12c.py 

And we can validate if there is something wrong in the generation to fix it.

Regards,
Jorge.

**Comment by sujansonly** [comment]
Hi Jorge,

issue has been fixed after i pass the attributes properly. got that by seeing your read me doc.
Scripts works like charm.

great job. Looking forward for your latest release.

Thank you.

**Comment by govin646** [comment]
Hi Sujan,

  I am also getting similar error like below and please let me know how do you address this issue.

## Error while creating Domain :

com.oracle.cie.domain.script.jython.WLSTException: No Server object with name **WLS_SOA1**
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2360)
        at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
Thanks,
Raja

**Comment by sujansonly** [comment]
Hi Jeqo,

I have solved the problems with your help.
Wanted to ask you one more things.

Can we use the same scripts to make the cluster SOA setup. ?
What would be the changes required for cluster setup?

Regards
Sujan

**Comment by sujansonly** [comment]
I could not find the solution for the above problem, i was missing
something for the Admin Server before and i solved that by passing correct
attributes.

How did u add a soa server to the domain ?

Regards
Sujan

**Comment by jeqo** [comment]
Hi guys,

@govin646: about your issue: it depends on your WSLT script. I suppose your are trying to update a server that does not exist or does not have that name yet. Could you show us your wlst script to check it?

@sujansonly: to create a cluster you need more steps related with customizing WSLT script to configure a managed servers and cluster, etc. I recommend you to use provisioning to install SOA suite in your nodes and then create your own wslt that helps you to configure a cluster.
