### ISSUE TITLE
Alter Datasource Fails

### ISSUE THREAD

**Issue by sujansonly** [jeqo/oracle-fmw#5]
scripts failing on below step.

[2016-01-15T12:39:38-05:00] INFO: Processing execute[/home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py         ] action run (oracle-fmw::create-domain-12c line 61)
[2016-01-15T12:44:49-05:00] INFO: Running queued delayed notifications before re-raising exception
[2016-01-15T12:44:49-05:00] INFO: template[/etc/postfix/main.cf] sending restart action to service[postfix](delayed)
[2016-01-15T12:44:49-05:00] INFO: Processing service[postfix] action restart (postfix::_common line 123)
[2016-01-15T12:44:49-05:00] INFO: service[postfix] restarted
[2016-01-15T12:44:49-05:00] ERROR: Running exception handlers
[2016-01-15T12:44:49-05:00] ERROR: Exception handlers complete
[2016-01-15T12:44:49-05:00] FATAL: Stacktrace dumped to /etc/ge/corp/local-mode-cache/cache/chef-stacktrace.out
[2016-01-15T12:44:49-05:00] ERROR: execute[/home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py](oracle-         fmw::create-domain-12c line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py ----
STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return          a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Adding Templates
Creating Resources
Error: cd() failed. Do dumpStack() to see details.
STDERR: Problem invoking WLST - Traceback (innermost last):
  File "/etc/ge/corp/local-mode-cache/cache/new_domain-12c.py", line 66, in ?
  File "/etc/ge/corp/local-mode-cache/cache/new_domain-12c.py", line 16, in alterDatasource
  File "/tmp/WLSTOfflineIni8269976080529373646.py", line 23, in cd
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
        at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:1069)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: java.lang.UnsupportedOperationException: Could not create          generic operation:JDBCDriverParams
---- End output of /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py ----
Ran /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py returned 1
[2016-01-15T17:44:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Any thing i am missing here.

**Comment by sujansonly** [comment]
I am trying to connect to remote machine, where i have installed oracle database.

**Comment by sujansonly** [comment]
Hi Jeqo,

I have tried installing all the softwares in the same box. than it throws the error saying username/password invalid

below is the stacktrance.

[2016-01-16T00:43:16-05:00] ERROR: Running exception handlers
[2016-01-16T00:43:16-05:00] ERROR: Exception handlers complete
[2016-01-16T00:43:18-05:00] FATAL: Stacktrace dumped to /etc/ge/corp/local-mode-cache/cache/chef-stacktrace.out
[2016-01-16T00:43:18-05:00] ERROR: execute[/home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py](oracle-fmw::create-domain-12c line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py ----
STDOUT: Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Adding Templates
Creating Resources
[EL Severe]: ejb: 2016-01-16 00:43:14.938--ServerSession(1798762074)--Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017
Error: updateDomain() failed. Do dumpStack() to see details.
STDERR: Problem invoking WLST - Traceback (innermost last):
  File "/etc/ge/corp/local-mode-cache/cache/new_domain-12c.py", line 79, in ?
  File "/tmp/WLSTOfflineIni9152967428586174691.py", line 103, in updateDomain

Domain Location: /home/oracle-fmw/work/domains/DefaultDomain

Reason: oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017

Exception:

oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017

```
    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
    at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
    at com.oracle.cie.domain.script.jython.WLScriptContext.updateDomain(WLScriptContext.java:827)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.ScriptException: Domain Extension Application Failed!

Domain Location: /home/oracle-fmw/work/domains/DefaultDomain

Reason: oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017

Exception:

oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017
---- End output of /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py ----
Ran /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py returned 1
[

**Comment by jeqo** [comment]
@sujansonly: did you manage to fix this? By default 11g and 12c domain creation scripts use a password: "welcome1" defined by this property: ['domain-12c']['db_repo_password']
Did you try to change it before running into this?

Cheers!

**Comment by sujansonly** [comment]
initially i used different password, which i used while installing the database.
but later i changed it to welcome1 still it throws me the same error.

**Comment by jeqo** [comment]
once installation fails, could you connect to your machine and check the wlst script generated (`create_domain_py = File.join(Chef::Config[:file_cache_path], "new_domain-12c.py")`), check if the password is ok and run it manually: `"#{wl_home}/common/bin/wlst.sh #{create_domain_py}"`

**Comment by sujansonly** [comment]
u know, i also made the same password for weblogic. 

below is the script content created.
DOMAIN_MODE='Expanded'
DOMAIN_PATH='/home/oracle-fmw/work/domains/DefaultDomain'
APP_PATH='/home/oracle-fmw/work/apps/DefaultDomain'
DOMAIN='DefaultDomain'
START_MODE='dev'
CROSSDOMAIN_ENABLED=true

ADMIN_USERNAME='weblogic'
ADMIN_PASSWORD='welcome1'

REPOS_DBURL='jdbc:oracle:thin:@localhost:1521:XE'
REPOS_DBUSER_PREFIX='DEV01'
REPOS_DBPASSWORD='welcome1'

def alterDatasource(datasource_name, schema_sufix, driver_name):
        cd('/JDBCSystemResource/' + datasource_name + '/JdbcResource/' + datasource_name + '/JDBCDriverParams/NO_NAME_0')
        set('URL',REPOS_DBURL)
        set('PasswordEncrypted',REPOS_DBPASSWORD)
        if driver_name:
                set('DriverName', driver_name)
        cd('Properties/NO_NAME_0/Property/user')
        set('Value',REPOS_DBUSER_PREFIX+'_'+schema_sufix)

def defineServer(default_name, new_name, machine_name, address, port):
        cd('/Servers/' + default_name)
        if machine_name:
                set('Machine', machine_name)
        if address:
                set('ListenAddress', address)
        set('ListenPort',port)
        set('Name',new_name)

print 'Creating Domain'

readTemplate('/home/oracle-fmw/fmw/12c/wlserver/common/templates/wls/wls.jar', DOMAIN_MODE)

setOption('ServerStartMode', START_MODE)
setOption('AppDir', APP_PATH )

cd('/')
cd('Security/base_domain/User/weblogic')
set('Name',ADMIN_USERNAME)
cmo.setPassword(ADMIN_PASSWORD)
"

i m going to run it manually.

**Comment by sujansonly** [comment]
oh it returned saying this...

[root@ip-10-227-83-104 gecloud]# /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py

Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Error: writeDomain() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/etc/ge/corp/local-mode-cache/cache/new_domain-12c.py", line 54, in ?
  File "/tmp/WLSTOfflineIni7129978096444931467.py", line 73, in writeDomain
60302: A domain already exists at the specified location.
60302: Change the domain location.
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
        at com.oracle.cie.domain.script.jython.WLScriptContext.writeDomain(WLScriptContext.java:1392)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.ScriptException: 60302: Domain already exists.
60302: A domain already exists at the specified location.
60302: Change the domain location.

Can you pls advice me, which folders do i have to remove to clean up the failed domain.

**Comment by sujansonly** [comment]
i just changed the location and ran the script... it throws the same error.

[root@ip-10-227-83-104 gecloud]# /home/oracle-fmw/fmw/12c/wlserver/common/bin/wlst.sh /etc/ge/corp/local-mode-cache/cache/new_domain-12c.py

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Domain
Adding Templates
Creating Resources
[EL Severe]: ejb: 2016-01-18 14:15:41.404--ServerSession(703896178)--Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017
Error: updateDomain() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/etc/ge/corp/local-mode-cache/cache/new_domain-12c.py", line 79, in ?
  File "/tmp/WLSTOfflineIni2038411101033053708.py", line 103, in updateDomain

Domain Location: /home/oracle-fmw/work/domains/DefaultDomain2

Reason: oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017

Exception:

oracle.security.opss.tools.lifecycle.LifecycleException: Error during configuring DB security store. Exception oracle.security.opss.tools.lifecycle.LifecycleException: oracle.security.jps.service.policystore.PolicyStoreException: javax.persistence.PersistenceException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

Error Code: 1017

```
    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
    at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
    at com.oracle.cie.domain.script.jython.WLScriptContext.updateDomain(WLScriptContext.java:827)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.ScriptException: Domain Extension Application Failed!

Domain Location: /home/oracle-fmw/work/domains/DefaultDomain2

---

Is it because the i created the oracle with oracle user and this script runs from root ?

**Comment by sujansonly** [comment]
which username does it picks up by default ?

**Comment by sujansonly** [comment]
[root@ip-10-227-83-104 gecloud]# sqlplus

SQL*Plus: Release 11.2.0.2.0 Production on Mon Jan 18 14:29:45 2016

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter user-name: sys
Enter password:
ERROR:
ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

Enter user-name: system
Enter password:

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>

**Comment by jeqo** [comment]
wlst is trying to connect database schemas that are created by RCU. Those schemas exist in you database? for instance: DEV_SOAINFRA or DEV_MDS (where DEV is the prefix that you choose in RCU)

**Comment by sujansonly** [comment]
i have not ran the BPM Setup.

Can i make the domain setup with out BPM ?

**Comment by jeqo** [comment]
Check this variable:

```
default['domain-12c']['apps'] = [
    {"name" => "OSB", "enabled" => false},
    {"name" => "SOA", "enabled" => false},
    {"name" => "BPM", "enabled" => false},
    {"name" => "BAM", "enabled" => false}
]
```

these vars let you decide which templates will be applied to your domain.

**Comment by sujansonly** [comment]
Hi Jeqo,

RCU seems to be installed form BPM setup file, isnt it ?
Can i have RCU setup without running BPM ? also i do not find BPM setup file for 12.1.3 which i am using for SOA setup.

Regards
Sujan

**Comment by sujansonly** [comment]
i was trying to run this role.

i want to install the soa domain
{
    "name" : "demo-soa-12c",
    "json_class" : "Chef::Role",
    "default_attributes" : {
        "fmw-12c": {
            "os_user": "oraclefmw"
        },
        "soa_qs-12c": {
            "url": "file:///data/fmw_12.1.3.0.0_soaqs_Disk1_1of1.zip"
        },
        "domain-12c": {
            "name": "demo-soa-domain",
            "mode": "Compact",
            "apps": [
                {"name" : "SOA", "enabled" : true},
                {"name" : "BPM", "enabled" : false},
                {"name" : "BAM", "enabled" : false},
                {"name" : "OSB", "enabled" : false}
            ],
            "machines": [
            ],
            "admin_server": {
                "base_name" : "AdminServer",
                "new_name" : "soa-server",
                "port" : "7001"
            },
            "managed_servers": [
            ]
        }
    },
    "run_list" : [
        "recipe[oracle-fmw::install-soa_qs-12c]",
        "recipe[oracle-fmw::create-domain-12c]"
    ]
}

SOA has installed and Create domains fails in this.
I have not put anything else in this run list. 

do i have to add install RCU or BPM Scripts also to setup SOA domain ?

**Comment by jeqo** [comment]
Compact mode uses derby database instead of Oracle Database, but https://github.com/jeqo/oracle-fmw/blob/master/templates/default/domain-12c.py.erb still update datasource. That could be causing this problem.
Could you try to add a conditional to update datasources if DOMAIN_MODE is compact? Hopefully I will have time this weekend to test this cookbook.

**Comment by jeqo** [comment]
@sujansonly this is resolved also?

**Comment by sujansonly** [comment]
yah... i added rcu in the runlist.
rcu home has bpm directory i made change the path nd it executed well.

how can i start the soa server inside the console. what are all the settings i need more to startup the soa server ?

**Comment by jeqo** [comment]
This cookbook does not include a "startup" service defined. You can start it as any other domain installation by running [domain home]/startWebLogic.sh if you have all services in AdminServer.
